---
title: "eds-212-day-2"
author: "Ryan Munnikhuis"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## First order univariate derivatives

```{r}
# Problem A
f_x = expression(x^2)

df_dx = D(expr = f_x, "x")

df_dx

x = 3

eval(expr = df_dx)

```

```{r}
# Problem B

p_a = expression(2*(3*a+2)^4-5)

df_da = D(expr = p_a, "a")

df_da 

a = 1.2

eval(expr = df_da)

```

```{r}
# Problem C 

g_t = expression((-4*t)/((t^2+1)^3))

gf_gt = D(expr = g_t, "t")

gf_gt

t = 0

eval(expr = gf_gt)

```
#Higher order derivatives 
```{r}
g_z = expression(4.6-1.9*z^3)

gf_dz = D(exp = g_z, "z")

gf_dz

g2_z2 = expression(-1.9*(3*z^2))

g2f_dz2 = D(exp = g2_z2, "z")

g2f_dz2

```
```{r}

#Partial derivatives 

f_x_y_Z = expression(2*x^2*y-3*x+1+4*z^4*x)

df_dx = D(exp = f_x_y_Z, "x")

df_dx

df_dy = D(exp = f_x_y_Z, "y")

df_dy

df_dz = D(exp = f_x_y_Z, "z")

df_dz
```
```{r}
f_x = function(x) {
  2.4 * exp(-.05 * x) * sin(x)
}
  
```

```{r}

ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) + geom_point(aes(color = species))


```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + geom_jitter() + 
  labs (x = "Species", 
        y = "Flipper length (mm)",
        title = "Penguin Species versus Flipper Length")
```

